### ISSUE TITLE
TypeError: Invalid file paths given! on upstart

### ISSUE THREAD

**Issue by mapcentia** [urbica/galton#80]
When running:
node index.js denmark.osrm

I get:

TypeError: Invalid file paths given!
    at TypeError (native)
    at Object.exports.default (/vagrant/galton/lib/server.js:1:493)
    at Object.<anonymous> (/vagrant/galton/index.js:112:22)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3

**Comment by stepankuzmin** [comment]
Hi there, @mapcentia! This problem can occur if you are using osrm file built with different OSRM version.

For example, `galton@1.3.4` uses `node-osrm@5.3.3`, so you can try build osrm file with `osrm-backend@5.3.3`. You can also try [How-To](https://github.com/urbica/galton/wiki/How-To) tutorial.

If this problem will still be there, feel free to reopen this issue.
