### ISSUE TITLE
TypeError: Fingeprint does not match

### ISSUE THREAD

**Issue by JamesMilnerUK** [urbica/galton#92]
Hey folks!

Awesome project, although I'm having a bit of a problem. When I run 

`galton greater-london-latest.osrm`

I receive the following error:
```

TypeError: Fingeprint does not match

/usr/lib/node_modules/galton/lib/server.js:1
(function (exports, require, module, __filename, __dirname) { 'use strict';Object.defineProperty(exports,"__esModule",{value:true});exports.defaults=undefined;var _regenerator=require('babel-runtime/regenerator');var _regenerator2=_interopRequireDefault(_regenerator);var _asyncToGenerator2=require('babel-runtime/helpers/asyncToGenerator');var _asyncToGenerator3=_interopRequireDefault(_asyncToGenerator2);exports.default=function(config){var _this=this;var app=new _koa2.default();var osrm=new _osrm2.default({path:config.osrmPath,shared_memory:!!config.sharedMemory});var defaultOptions={osrm:osrm,bufferSize:config.bufferSize||defaults.bufferSize,cellWidth:config.cellWidth||defaults.cellWidth,concavity:config.concavity||defaults.concavity,intervals:config.intervals||defaults.intervals,lengthThreshold:config.lengthThreshold||defaults.lengthThreshold,resolution:config.resolution||defaults.resolution,sharpness:config.sharpness||defaults.sharpness,units:config.units||def

TypeError: Fingeprint does not match in greater-london-latest.osrm.icd
    at TypeError (native)
    at Object.exports.default (/usr/lib/node_modules/galton/lib/server.js:1:493)
    at Object.<anonymous> (/usr/lib/node_modules/galton/index.js:112:22)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3


```

Anyone have any ideas why this might be? the OSRM file was built from geofabrik pbf data for London using the standard OSRM-backend compiled from source.

**Comment by stepankuzmin** [comment]
Hi there @JamesMilnerUK! Which version of osrm-backend and galton do you use?

**Comment by chrismayer** [comment]
Hi all,
I am running into the same issue as reported by @JamesMilnerUK. Here some version informations of my setup:

- Galton: v1.3.5
- OSRM (used in Galton): v5.3.0
- OSRM (to create the *.osrm files): v5.3.0
- node: v4.6.0
- npm: v2.15.9
- OS: Ubuntu 14.04 (LTS)

Thanks for any help!

**Comment by stepankuzmin** [comment]
I think that you should try osrm-backend v5.3.3 with galton v 1.3.5 https://github.com/urbica/galton/wiki/How-To

**Comment by chrismayer** [comment]
Hi @stepankuzmin,

thanks for your quick reply. I tried with OSRM 5.3.3 and now it works like charme. This is a really great tool! Thanks for your help.

Cheers
Chris

**Comment by stepankuzmin** [comment]
Great!

**Comment by JamesMilnerUK** [comment]
Unfortunately I followed those instructions and am receiving the same error :(

**Comment by stepankuzmin** [comment]
@JamesMilnerUK could you please provide your software setup versions?
